<a href="https://colab.research.google.com/github/Sweetydutta8/hello-world/blob/master/churnmodelling%20using%20machine%20learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from matplotlib import pyplot

In [4]:
from google.colab import files
files=files.upload()

Saving datasets_13996_18858_WA_Fn-UseC_-Telco-Customer-Churn.csv to datasets_13996_18858_WA_Fn-UseC_-Telco-Customer-Churn (1).csv


In [0]:
customer_churn=pd.read_csv('datasets_13996_18858_WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [0]:
#importing machine learning libraries
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

#Linear Regression
y=customer_churn[['MonthlyCharges']]
x=customer_churn[['tenure']]

In [0]:
#dividing the dataset into 70:30 ratio
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)

In [9]:
#to build the model on train set and predict values on test set
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((4930, 1), (4930, 1), (2113, 1), (2113, 1))

In [10]:
regressor = LinearRegression()

regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
y_pred=regressor.predict(x_test)
y_pred[:5],y_test[:5]

(array([[60.95089608],
        [72.98096699],
        [59.1903979 ],
        [55.66940154],
        [71.51388517]]),       MonthlyCharges
 2200           58.20
 4627          116.60
 3225           71.95
 2828           20.45
 3768           77.75)

In [12]:
#to find the root mean square error
from sklearn.metrics import mean_squared_error

np.sqrt(mean_squared_error(y_test,y_pred))

29.394584027273893

In [0]:
#Logistic Regression
x=customer_churn[['MonthlyCharges']]
y=customer_churn[['Churn']]

In [0]:
#dividing the datset into 65:35 ratio
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.35,random_state=0)

In [16]:
#to build a model on train set and predict the values on test set
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression()

log_model.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
y_pred=log_model.predict(x_test)

In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score


In [19]:
confusion_matrix(y_test,y_pred),accuracy_score(y_test,y_pred)

(array([[1815,    0],
        [ 651,    0]]), 0.7360097323600974)

In [20]:
#checking accuracy
(1815)/(1815+651)

0.7360097323600974

In [0]:
#to build a decision tree
x=customer_churn[['MonthlyCharges']]
y=customer_churn[['Churn']]

from sklearn.tree import DecisionTreeClassifier

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [22]:
my_tree = DecisionTreeClassifier()

my_tree.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [0]:
#to build the model on train set and predict the value on test set
y_pred=my_tree.predict(x_test)

In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [25]:
confusion_matrix(y_test,y_pred)

array([[901, 140],
       [301,  67]])

In [26]:
#checking accuracy
(965+87)/(965+87+281+76)

0.7466288147622427

In [27]:
#to build a random forest model
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [28]:
#to build the model on train set and predict the value in test set
rf.predict(x_test)

array(['No', 'No', 'No', ..., 'No', 'No', 'Yes'], dtype=object)

In [29]:
confusion_matrix(y_test,y_pred)

array([[901, 140],
       [301,  67]])

In [30]:
#checking accuracy
accuracy_score(y_test,y_pred)

0.6870120652945352